In [33]:
import numpy as np
import pandas as pd
import os

In [2]:
!pip install --pre pycaret

Requirement already satisfied: pycaret in c:\users\sony6\.conda\envs\tf\lib\site-packages (3.1.0)
Requirement already satisfied: ipython>=5.5.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (8.15.0)
Requirement already satisfied: ipywidgets>=7.6.5 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (8.1.0)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (4.66.1)
Collecting numpy<1.24,>=1.21 (from pycaret)
  Downloading numpy-1.23.5-cp39-cp39-win_amd64.whl (14.7 MB)
     ---------------------------------------- 0.0/14.7 MB ? eta -:--:--
     ---------------------------------------- 0.1/14.7 MB 1.3 MB/s eta 0:00:11
     - -------------------------------------- 0.5/14.7 MB 5.7 MB/s eta 0:00:03
     --- ------------------------------------ 1.1/14.7 MB 7.8 MB/s eta 0:00:02
     ---- ----------------------------------- 1.7/14.7 MB 8.9 MB/s eta 0:00:02
     ------ --------------------------------- 2.2/14.7 MB 9.5 MB/s eta 0:00:02
     ------- -------------------------------- 2.8/14.7 MB 9.8 MB/s eta 0:00:02
     --------- ------------------------------ 3.3/14.7 MB 10.1 MB/s eta 0:00:02
     ---------- ----------------------------- 3.9/14.7 MB 10.3 MB/s eta 0:00:02
     ------------ --------------------------- 4.4/14.7 MB 10.4 MB/s eta 0:00:01
     ------------- -------------------------- 4.9/14.7 MB 10.5 MB/s eta 0:00:01
     -------------- ------------------------- 5.5/14.7 MB 10.7 MB/s eta 0:00:01
     ---------------- ----------------------- 6.0/14.7 MB 10.7 MB/s eta 0:00:01
     ----------------- ---------------------- 6.5/14.7 MB 10.7 MB/s eta 0:00:01
     ------------------- -------------------- 7.1/14.7 MB 10.9 MB/s eta 0:00:01
     -------------------- ------------------- 7.7/14.7 MB 10.9 MB/s eta 0:00:01
     --------------------- ------------------ 8.0/14.7 MB 10.9 MB/s eta 0:00:01
     ----------------------- ---------------- 8.7/14.7 MB 10.9 MB/s eta 0:00:01
     ------------------------- -------------- 9.3/14.7 MB 11.0 MB/s eta 0:00:01
     ------------------------- -------------- 9.4/14.7 MB 11.0 MB/s eta 0:00:01
     ------------------------- -------------- 9.4/14.7 MB 11.0 MB/s eta 0:00:01
     -------------------------- ------------- 9.7/14.7 MB 10.0 MB/s eta 0:00:01
     --------------------------- ----------- 10.3/14.7 MB 10.4 MB/s eta 0:00:01
     ---------------------------- ---------- 10.7/14.7 MB 10.4 MB/s eta 0:00:01
     ----------------------------- --------- 11.1/14.7 MB 10.2 MB/s eta 0:00:01
     ------------------------------ -------- 11.6/14.7 MB 10.2 MB/s eta 0:00:01
     ------------------------------- ------- 12.0/14.7 MB 10.1 MB/s eta 0:00:01
     --------------------------------- ----- 12.5/14.7 MB 10.1 MB/s eta 0:00:01
     ---------------------------------- ---- 13.0/14.7 MB 10.1 MB/s eta 0:00:01
     ----------------------------------- --- 13.5/14.7 MB 10.1 MB/s eta 0:00:01
     ------------------------------------- - 14.1/14.7 MB 10.1 MB/s eta 0:00:01
     ---------------------------------------  14.6/14.7 MB 9.9 MB/s eta 0:00:01
     ---------------------------------------- 14.7/14.7 MB 9.6 MB/s eta 0:00:00
Requirement already satisfied: pandas<2.0.0,>=1.3.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (1.5.2)
Requirement already satisfied: jinja2>=1.2 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: scipy~=1.10.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (1.10.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (1.3.2)
Requirement already satisfied: scikit-learn<1.3.0,>=1.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: pyod>=1.0.8 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (1.1.0)
Requirement already satisfied: imbalanced-learn>=0.8.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (0.11.0)
Requirement already satisfied: category-encoders>=2.4.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (2.6.2)
Requirement already satisfied: lightgbm>=3.0.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (3.3.5)
Requirement already satisfied: numba>=0.55.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (0.57.1)
Requirement already satisfied: requests>=2.27.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (2.31.0)
Requirement already satisfied: psutil>=5.9.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (5.9.5)
Requirement already satisfied: markupsafe>=2.0.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (2.1.3)
Requirement already satisfied: importlib-metadata>=4.12.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (5.2.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (5.9.2)
Requirement already satisfied: cloudpickle in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (2.2.1)
Requirement already satisfied: deprecation>=2.1.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (3.3.0)
Requirement already satisfied: matplotlib>=3.3.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (3.7.2)
Requirement already satisfied: scikit-plot>=0.3.7 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.0.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (5.16.1)
Requirement already satisfied: kaleido>=0.2.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (0.2.1)
Requirement already satisfied: schemdraw==0.15 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (0.9.1)
Requirement already satisfied: statsmodels>=0.12.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (0.14.0)
Requirement already satisfied: sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (0.21.1)
Requirement already satisfied: tbats>=1.1.3 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima!=1.8.1,<3.0.0,>=1.8.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pycaret) (2.0.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from category-encoders>=2.4.0->pycaret) (0.5.3)
Requirement already satisfied: packaging in c:\users\sony6\.conda\envs\tf\lib\site-packages (from deprecation>=2.1.0->pycaret) (21.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from imbalanced-learn>=0.8.1->pycaret) (3.2.0)
Requirement already satisfied: zipp>=0.5 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (3.16.2)
Requirement already satisfied: backcall in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: decorator in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (0.19.0)
Requirement already satisfied: matplotlib-inline in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: pickleshare in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (2.16.1)
Requirement already satisfied: stack-data in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (0.6.2)
Requirement already satisfied: traitlets>=5 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (5.9.0)
Requirement already satisfied: typing-extensions in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (4.7.1)
Requirement already satisfied: exceptiongroup in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (1.1.3)
Requirement already satisfied: colorama in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: comm>=0.1.3 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (0.1.4)
Requirement already satisfied: widgetsnbextension~=4.0.7 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.8)
Requirement already satisfied: jupyterlab-widgets~=3.0.7 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.8)
Requirement already satisfied: wheel in c:\users\sony6\.conda\envs\tf\lib\site-packages (from lightgbm>=3.0.0->pycaret) (0.41.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from matplotlib>=3.3.0->pycaret) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from matplotlib>=3.3.0->pycaret) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from matplotlib>=3.3.0->pycaret) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from matplotlib>=3.3.0->pycaret) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from matplotlib>=3.3.0->pycaret) (8.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from matplotlib>=3.3.0->pycaret) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from matplotlib>=3.3.0->pycaret) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from matplotlib>=3.3.0->pycaret) (6.0.1)
Requirement already satisfied: fastjsonschema in c:\users\sony6\.conda\envs\tf\lib\site-packages (from nbformat>=4.2.0->pycaret) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from nbformat>=4.2.0->pycaret) (4.19.0)
Requirement already satisfied: jupyter-core in c:\users\sony6\.conda\envs\tf\lib\site-packages (from nbformat>=4.2.0->pycaret) (5.3.1)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from numba>=0.55.0->pycaret) (0.40.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pandas<2.0.0,>=1.3.0->pycaret) (2023.3.post1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from plotly>=5.0.0->pycaret) (8.2.3)
Requirement already satisfied: dash<3.0.0,>=2.11.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (2.13.0)
Requirement already satisfied: orjson<4.0.0,>=3.8.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.9.7)
Requirement already satisfied: trace-updater>=0.0.8 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.0.9.1)
Requirement already satisfied: tsdownsample==0.1.2 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.2)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (3.0.2)
Requirement already satisfied: urllib3 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (1.26.16)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (68.1.2)
Requirement already satisfied: six in c:\users\sony6\.conda\envs\tf\lib\site-packages (from pyod>=1.0.8->pycaret) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from requests>=2.27.1->pycaret) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from requests>=2.27.1->pycaret) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from requests>=2.27.1->pycaret) (2023.7.22)
Requirement already satisfied: deprecated>=1.2.13 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret) (1.2.14)
Requirement already satisfied: scikit-base<0.6.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret) (0.5.1)
Requirement already satisfied: Flask<2.3.0,>=1.0.4 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.3)
Requirement already satisfied: Werkzeug<2.3.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.3)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (5.0.0)
Requirement already satisfied: retrying in c:\users\sony6\.conda\envs\tf\lib\site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.3.4)
Requirement already satisfied: ansi2html in c:\users\sony6\.conda\envs\tf\lib\site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.8.0)
Requirement already satisfied: nest-asyncio in c:\users\sony6\.conda\envs\tf\lib\site-packages (from dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.5.6)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from deprecated>=1.2.13->sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret) (1.15.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.10.2)
Requirement already satisfied: wcwidth in c:\users\sony6\.conda\envs\tf\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.5.0->pycaret) (0.2.6)
Requirement already satisfied: platformdirs>=2.5 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (304)
Requirement already satisfied: executing>=1.2.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.4.0)
Requirement already satisfied: pure-eval in c:\users\sony6\.conda\envs\tf\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from Flask<2.3.0,>=1.0.4->dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.1.2)
Requirement already satisfied: click>=8.0 in c:\users\sony6\.conda\envs\tf\lib\site-packages (from Flask<2.3.0,>=1.0.4->dash<3.0.0,>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (8.1.7)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.3
    Uninstalling numpy-1.24.3:
      Successfully uninstalled numpy-1.24.3
Successfully installed numpy-1.23.5

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mlflow 1.30.1 requires pytz<2023, but you have pytz 2023.3.post1 which is incompatible.
scikit-image 0.21.0 requires pillow>=9.0.1, but you have pillow 8.4.0 which is incompatible.
tensorflow-intel 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.7.1 which is incompatible.

In [34]:
from pycaret.classification import *

In [35]:
df=pd.read_csv('C:/Users/sony6/OneDrive/바탕 화면/AMEX_PREDICTION_DEFAULT/train_data.csv', nrows=450000)
df1=pd.read_csv('C:/Users/sony6/OneDrive/바탕 화면/AMEX_PREDICTION_DEFAULT/train_labels.csv',low_memory=True, nrows=450000)

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df1.head()

                                         customer_ID  target
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...       0
1  00000fd6641609c6ece5454664794f0340ad84dddce9a2...       0
2  00001b22f846c82c51f6e3958ccd81970162bae8b007e8...       0
3  000041bdba6ecadd89a52d11886e8eaaec9325906c9723...       0
4  00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...       0

In [38]:
df=pd.merge(df,df1, on=['customer_ID'])

In [39]:
test_df=pd.read_csv('C:/Users/sony6/OneDrive/바탕 화면/AMEX_PREDICTION_DEFAULT/test_data.csv', nrows=200000)

In [40]:
sam_df=pd.read_csv('C:/Users/sony6/OneDrive/바탕 화면/AMEX_PREDICTION_DEFAULT/sample_submission.csv',low_memory=True, nrows=200000)

In [41]:
s=setup(data=df.drop(['customer_ID', 'S_2'], axis=1),target='target')

In [13]:
best=compare_models()

In [45]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [47]:
model=create_model('et')

In [48]:
pred=predict_model(model,data=test_df.drop(['customer_ID', 'S_2'], axis=1),raw_score=False)

In [49]:
pred

,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,...,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,prediction_label,prediction_score
0,0.631315,0.001912,0.010728,0.814497,0.007547,0.168651,0.009971,0.002347,0.113189,NaN,...,NaN,NaN,0.004669,NaN,NaN,NaN,0.008281,NaN,0,0.63
1,0.587042,0.005275,0.011026,0.810848,0.001817,0.241389,0.000166,0.009132,0.123035,NaN,...,NaN,0.000142,0.004940,0.009021,NaN,0.003695,0.003753,0.001460,0,0.69
2,0.609056,0.003326,0.016390,1.004620,0.000114,0.266976,0.004196,0.004192,0.125319,NaN,...,NaN,0.000074,0.002114,0.004656,NaN,0.003155,0.002156,0.006482,0,0.81
3,0.614911,0.009065,0.021672,0.816549,0.009722,0.188947,0.004123,0.015325,0.123438,NaN,...,NaN,0.004743,0.006392,0.002890,NaN,0.006044,0.005206,0.007855,0,0.78
4,0.591673,0.238794,0.015923,0.810456,0.002026,0.180035,0.000731,0.011281,0.122212,NaN,...,NaN,0.008133,0.004329,0.008384,NaN,0.001008,0.007421,0.009471,0,0.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,0.970498,0.002181,0.024811,1.005625,0.007744,0.120094,0.001749,0.008977,NaN,NaN,...,NaN,0.000909,0.008055,0.007320,NaN,0.006766,0.000397,0.001822,0,1.00
199996,0.939550,0.623800,0.045650,1.005876,0.003873,0.120999,0.004597,0.002064,NaN,NaN,...,NaN,0.007272,0.001824,0.004888,NaN,0.008211,0.008926,0.005498,0,1.00
199997,0.935420,0.215794,0.036632,1.008096,0.008109,0.111907,0.001784,0.001253,NaN,NaN,...,NaN,0.002692,0.003650,0.008935,NaN,0.002047,0.000849,0.006140,0,1.00
199998,0.941477,0.179642,0.027573,1.008244,0.003870,0.124180,0.001205,0.002556,NaN,NaN,...,NaN,0.009399,0.009096,0.000486,NaN,0.001375,0.003065,0.006802,0,1.00
199999,0.939218,0.090217,0.042124,1.004468,0.000544,0.129382,0.004719,0.000294,NaN,NaN,...,NaN,0.002409,0.009358,0.007805,NaN,0.001107,0.009979,0.007870,0,1.00

In [56]:
sam_df['prediction']=pred['prediction_label']

In [57]:
sam_df

                                              customer_ID  prediction
0       00000469ba478561f23a92a868bd366de6f6527a684c9a...           0
1       00001bf2e77ff879fab36aa4fac689b9ba411dae63ae39...           0
2       0000210045da4f81e5f122c6bde5c2a617d03eef67f82c...           0
3       00003b41e58ede33b8daf61ab56d9952f17c9ad1c3976c...           0
4       00004b22eaeeeb0ec976890c1d9bfc14fd9427e98c4ee9...           0
...                                                   ...         ...
199995  3764bc8412d6f3a3316f239620121c28f721dc4e5cef44...           0
199996  3764d984f88196f8bde70b32fd7369d1ea546324281b68...           0
199997  3764f1d98cf43ada3795baae51f5097c21fed6eba6c8df...           0
199998  37650a4275d62c34c6ef0a5a644ef951f33d1a6e040e55...           0
199999  3765271e971530da7ce75bf6e959ec29b379aa066361da...           0

[200000 rows x 2 columns]

In [58]:
sam_df.to_csv('C:/Users/sony6/OneDrive/바탕 화면/AMEX_RESULT/ExtraTree_submission.csv')

In [59]:
# 앙상블
blender = blend_models(estimator_list=compare_models(n_select=5))

In [60]:
evaluate_model(blender)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [61]:
final = finalize_model(blender)

In [62]:
y_pred = predict_model(final, data=test_df.drop(['customer_ID', 'S_2']))
y_pred

KeyError: "['customer_ID', 'S_2'] not found in axis"

In [ ]:
y_pred.shape,sam_df.shape

In [ ]:
y_pred.columns

In [ ]:
pred = y_pred['Label']
sam_df['prediction']=pred
sam_df.head()